### PR TITLE
updated the meata of Description

### PR DESCRIPTION
**Pull request by 000Andre000**
update

updated the description in meta

### CODE REVIEW

**Comment by haydencordeiro** [comment]
@000Andre000 can you use the event description rather than the title? The title is already being used in the previous meta tag

**Review by haydencordeiro — CHANGES_REQUESTED** [review]
Use event description instead of title

**Comment by 000Andre000** [comment]
There is no descriotion field added form the graph thingy i.e. from where
the new events are added and i dont have access to it so i did this

**Comment by grejojoby** [comment]
We can think of adding the desc field to graphcms as well i guess

**Comment by haydencordeiro** [comment]
@000Andre000 @grejojoby , I have raised a fix pr and updated the issue
https://github.com/flockflair-dbit/acm-website/issues/47#issuecomment-1976578693

**Pull request closed without merging**
